<a href="https://colab.research.google.com/github/MichalJagielo/DataScience_ExercisesPractice_Python/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__
# import pandas as pd
# pd.__version__

'1.1.5'

In [4]:
price = np.array([[12.40, 12.23, 14.36, 100],
                 [12.50, 12.30, 12.48, 200],
                 [12.20, 12.36, 12.58, 300]])

print(price)

[[ 12.4   12.23  14.36 100.  ]
 [ 12.5   12.3   12.48 200.  ]
 [ 12.2   12.36  12.58 300.  ]]


In [6]:
price.sum()
np.sum(price)

713.41

In [13]:
price.sum(axis=1)
price.sum(axis=0)

array([138.99, 237.28, 337.14])

In [22]:
np.min(price, axis=0)
np.max(price, axis=0)
np.median(price)
np.mean(price, axis=0)
np.std(price, axis=0)
np.var(price, axis=0)


array([1.55555556e-02, 2.82222222e-03, 7.45866667e-01, 6.66666667e+03])

In [29]:
x = np.array([1, 2, 3])
x
type(x)
x.ndim
x.shape
x.size
x.dtype

dtype('int64')

In [32]:
np.array([1.2, 2.3, 3.4])
x = np.array([1.2, 2.3, 3.4])
print(x)

[1.2 2.3 3.4]


In [36]:
x = np.array([[1, 3],
             [-1, 2]])
x
x.ndim
x.shape
x.dtype

dtype('int64')

In [39]:
x = np.array([[1, 3],[-1, 2],[2, -4]])
x
x.shape
x.size

6

In [42]:
A = np.array([1.2, 2.1, 3.4])
A.dtype

dtype('float64')

In [43]:
A = np.array([1.2, 2.1, 3.4], dtype='int')
A.dtype

dtype('int64')

In [45]:
A = np.array([1, 2, 3], dtype='complex')
A
A.dtype

dtype('complex128')

In [50]:
A = np.array([24,120,230],dtype = np.int8)
A
A.dtype
A

array([ 24, 120, -26], dtype=int8)

In [51]:
A = np.array([24,120,230], dtype = np.uint8)
A

array([ 24, 120, 230], dtype=uint8)

In [53]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
np.full(shape=(3,3), fill_value= [1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(start=5, stop=15, step=2)

array([ 5,  7,  9, 11, 13])

In [69]:
np.arange(start=1, stop=0, step=-0.05)

array([1.  , 0.95, 0.9 , 0.85, 0.8 , 0.75, 0.7 , 0.65, 0.6 , 0.55, 0.5 ,
       0.45, 0.4 , 0.35, 0.3 , 0.25, 0.2 , 0.15, 0.1 , 0.05])

In [71]:
np.linspace(start=0, stop=1, num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [81]:
A= np.arange(12)
A
#A.reshape((3,5))
A.reshape((3, -1))
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [82]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)


[3 1 4 2]
[ 3 -1  3  2]


In [91]:
A+B
np.add(A,B)

array([6, 0, 7, 4])

In [92]:
A-B
np.subtract(A,B)
A*B
np.multiply(A,B)
A/B
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [89]:
A + 3

array([6, 4, 7, 5])

In [90]:
A + 3*B

array([12, -2, 13,  8])

In [95]:
X = np.array([[1,3], [-2, 0]])
Y = np.array([[6,0], [-1,2]])
print(X)
print()
print(Y)

[[ 1  3]
 [-2  0]]

[[ 6  0]
 [-1  2]]


In [96]:
X*Y

array([[6, 0],
       [2, 0]])

In [97]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [98]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [99]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [100]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [101]:
np.random.seed(0)

In [104]:
np.random.randn()
np.random.randn(10)
np.random.randn(10, 4)

array([[-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628]])

In [107]:
np.random.rand()
np.random.rand(10)
np.random.rand(10, 2)

array([[0.57615733, 0.59204193],
       [0.57225191, 0.22308163],
       [0.95274901, 0.44712538],
       [0.84640867, 0.69947928],
       [0.29743695, 0.81379782],
       [0.39650574, 0.8811032 ],
       [0.58127287, 0.88173536],
       [0.69253159, 0.72525428],
       [0.50132438, 0.95608363],
       [0.6439902 , 0.42385505]])

In [113]:
np.random.randint(10)
np.random.randint(3, 13, size=5)

array([ 5, 11,  9,  9, 12])

In [115]:
np.random.choice([1,2,3,4,5,6,7])

7

In [116]:
np.random.choice(['ssss', 'dddd', 'fff'])

'ssss'

In [124]:
data = np.arange(10)
data
np.random.shuffle(data)
data

array([6, 8, 9, 2, 3, 7, 4, 0, 5, 1])

In [126]:
np.exp([1,2,3])

array([ 2.71828183,  7.3890561 , 20.08553692])

In [133]:
np.sqrt(9)
np.all((3,4,5,6))
np.any([0,0,0])

False

In [147]:
A = np.random.rand(5)
A

array([0.53657921, 0.89667129, 0.99033895, 0.21689698, 0.6630782 ])

In [151]:
np.argmax(A)

2

In [154]:
A[np.argmax(A)]
A[np.argmin(A)]

0.21689698439847394

In [155]:
np.argsort(A)

array([3, 0, 4, 1, 2])

In [160]:
np.max(A)
np.min(A)
np.mean(A)
np.median(A)
np.std(A)

0.2744875329359364

In [161]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [172]:
A[8]
A[:5]
A[5:]
A[5:11]
A[-10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [174]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [185]:
A[2]
A[:,2]
A[2,3]
A[1:3,1:4]
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [188]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [189]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [192]:
A.reshape(5,4)
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [202]:
B = A.T
print(B)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2 14 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [208]:
A = np.arange(-10, 10, 0.5)
A = A.reshape(10, -1)
A
A > 0
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [209]:
#A[A > -5 and A < 5]
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [210]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [212]:
np.bitwise_or(A<-5,A>5)
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])

In [216]:
v1 = np.array([0,4])
v1
np.linalg.norm(v1)

4.0

In [217]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [218]:
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p - q)

5.0

In [219]:
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p - q)

5.0990195135927845

In [220]:
# Matrix
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X)
print()
print(Y)

[[5 3]
 [3 9]]

[[ 1]
 [-1]]


In [223]:
Z = np.dot(X,Y)
Z
Z.shape

(2, 1)

In [225]:
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,1,-1],[0,-1,2],[3,2,0]])
print(X)
print()
print(Y)

[[ 2 -1  3]
 [ 3  1  0]]

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [230]:
Z = np.dot(X,Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [233]:
A = np.array([[2,4],[-1,3]])
np.linalg.det(A)
round(np.linalg.det(A))

10

In [237]:
A = np.array([[2,4,3],[-1,2,4]])
np.trace(A)

4

In [238]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [240]:
A = np.array([[2,4],[-1,3]])
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [243]:
np.set_printoptions(precision=4, suppress=True)

np.dot(A,B)
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [245]:
A = np.array([[2,4,3],[-1,2,4]])
np.transpose(A)
A.T

array([[ 2, -1],
       [ 4,  2],
       [ 3,  4]])

In [247]:
# 2x+4y=10
# x-y=-1
# x=1
# y=2
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])
A_inv = np.linalg.inv(A)
X=np.dot(A_inv,B) 
X

array([[1.],
       [2.]])